name: Deployment

on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly secret JWT_SECRET
        working-directory: lab07-jwt-auth
        run: flyctl secrets set JWT_SECRET="${{ secrets.JWT_SECRET }}" --app lab06
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        working-directory: lab07-jwt-auth
        run: flyctl deploy --remote-only --app lab06
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}